//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WebApplication6.WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccelerationUnitSoap", Namespace="http://www.webserviceX.NET/")]
    public partial class AccelerationUnit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeAccelerationUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccelerationUnit() {
            this.Url = global::WebApplication6.Properties.Settings.Default.WebApplication6_WS_AccelerationUnit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeAccelerationUnitCompletedEventHandler ChangeAccelerationUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ChangeAccelerationUnit", RequestNamespace="http://www.webserviceX.NET/", ResponseNamespace="http://www.webserviceX.NET/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ChangeAccelerationUnit(double AccelerationValue, Accelerations fromAccelerationUnit, Accelerations toAccelerationUnit) {
            object[] results = this.Invoke("ChangeAccelerationUnit", new object[] {
                        AccelerationValue,
                        fromAccelerationUnit,
                        toAccelerationUnit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeAccelerationUnitAsync(double AccelerationValue, Accelerations fromAccelerationUnit, Accelerations toAccelerationUnit) {
            this.ChangeAccelerationUnitAsync(AccelerationValue, fromAccelerationUnit, toAccelerationUnit, null);
        }
        
        /// <remarks/>
        public void ChangeAccelerationUnitAsync(double AccelerationValue, Accelerations fromAccelerationUnit, Accelerations toAccelerationUnit, object userState) {
            if ((this.ChangeAccelerationUnitOperationCompleted == null)) {
                this.ChangeAccelerationUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeAccelerationUnitOperationCompleted);
            }
            this.InvokeAsync("ChangeAccelerationUnit", new object[] {
                        AccelerationValue,
                        fromAccelerationUnit,
                        toAccelerationUnit}, this.ChangeAccelerationUnitOperationCompleted, userState);
        }
        
        private void OnChangeAccelerationUnitOperationCompleted(object arg) {
            if ((this.ChangeAccelerationUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeAccelerationUnitCompleted(this, new ChangeAccelerationUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Accelerations {
        
        /// <remarks/>
        celo,
        
        /// <remarks/>
        centigal,
        
        /// <remarks/>
        centimeterPersquaresecond,
        
        /// <remarks/>
        decigal,
        
        /// <remarks/>
        decimeterPersquaresecond,
        
        /// <remarks/>
        dekameterPersquaresecond,
        
        /// <remarks/>
        footPersquaresecond,
        
        /// <remarks/>
        gunit,
        
        /// <remarks/>
        gal,
        
        /// <remarks/>
        galileo,
        
        /// <remarks/>
        gn,
        
        /// <remarks/>
        grav,
        
        /// <remarks/>
        hectometerPersquaresecond,
        
        /// <remarks/>
        inchPersquaresecond,
        
        /// <remarks/>
        kilometerPerhoursecond,
        
        /// <remarks/>
        kilometerPersquaresecond,
        
        /// <remarks/>
        leo,
        
        /// <remarks/>
        meterPersquaresecond,
        
        /// <remarks/>
        milePerhourminute,
        
        /// <remarks/>
        milePerhoursecond,
        
        /// <remarks/>
        milePersquaresecond,
        
        /// <remarks/>
        milligal,
        
        /// <remarks/>
        millimeterPersquaresecond,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChangeAccelerationUnitCompletedEventHandler(object sender, ChangeAccelerationUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeAccelerationUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeAccelerationUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591